### ISSUE TITLE
Release needed: currently installing force JupyterLab==3.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterlab-contrib/jupyterlab-kernelspy#26]
Installing this package downgrades my JupyterLab 3.0.6 to 3.0.0, and it seems to relate to a requirement of `jupyterlab~=3.0.0b6` from some place.

Using `pipdeptree` I found...

```
jupyterlab-kernelspy==3.0.1
  - jupyterlab [required: ~=3.0.0b6, installed: 3.0.0]
```

Inspecting [the release history at pypi](https://pypi.org/project/jupyterlab-kernelspy/#history) I found the last release was made in september 2020.

From inspecting the current `setup.py` it seems to be more permissive than before though as of a commit made in January: ab7fa88b07eae2d995626cb5041744ac38fd4919

## Conclusion
A release is needed for proper JupyterLab 3 support beyond 3.0.0! Thanks for your work on this extension! :heart:

**Comment by fcollonval** [comment]
Thanks @consideRatio 

We need to finish porting this one on the latest cookiecutter extension structure and then release it. Should be shortly.

**Comment by fcollonval** [comment]
@consideRatio 3.0.2 was just released. It should fix it.
